### PR TITLE
Fix for NVIDIA nvc++ compiler

### LINKED ISSUE #2: Unable to compile with Nvidia nvc++ compiler due to static data member
When trying to compile PhysiCell with the Nvidia nvc++ compiler, the following linker error arises:
```
/cm/shared/apps/gcc/12.3.0/bin/ld: PhysiCell_constants.o: in function `__sti___30___core_PhysiCell_constants_cpp_d2e95040':
nvc++CNZeluOJ1fgTL.ll:(.text+0xb4): undefined reference to `PhysiCell::PhysiCell_constants::advanced_Ki67_cycle_model'
/cm/shared/apps/gcc/12.3.0/bin/ld: nvc++CNZeluOJ1fgTL.ll:(.text+0xc4): undefined reference to `PhysiCell::PhysiCell_constants::advanced_Ki67_cycle_model'
/cm/shared/apps/gcc/12.3.0/bin/ld: nvc++CNZeluOJ1fgTL.ll:(.text+0x118): undefined reference to `PhysiCell::PhysiCell_constants::basic_Ki67_cycle_model'
/cm/shared/apps/gcc/12.3.0/bin/ld: nvc++CNZeluOJ1fgTL.ll:(.text+0x120): undefined reference to `PhysiCell::PhysiCell_constants::basic_Ki67_cycle_model'
/cm/shared/apps/gcc/12.3.0/bin/ld: nvc++CNZeluOJ1fgTL.ll:(.text+0x158): undefined reference to `PhysiCell::PhysiCell_constants::flow_cytometry_cycle_model'
/cm/shared/apps/gcc/12.3.0/bin/ld: nvc++CNZeluOJ1fgTL.ll:(.text+0x164): undefined reference to `PhysiCell::PhysiCell_constants::live_cells_cycle_model'
/cm/shared/apps/gcc/12.3.0/bin/ld: nvc++CNZeluOJ1fgTL.ll:(.text+0x19c): undefined reference to `PhysiCell::PhysiCell_constants::flow_cytometry_cycle_model'
/cm/shared/apps/gcc/12.3.0/bin/ld: nvc++CNZeluOJ1fgTL.ll:(.text+0x1c4): undefined reference to `PhysiCell::PhysiCell_constants::live_cells_cycle_model'
/cm/shared/apps/gcc/12.3.0/bin/ld: nvc++CNZeluOJ1fgTL.ll:(.text+0x1f4): undefined reference to `PhysiCell::PhysiCell_constants::flow_cytometry_separated_cycle_model'
/cm/shared/apps/gcc/12.3.0/bin/ld: nvc++CNZeluOJ1fgTL.ll:(.text+0x230): undefined reference to `PhysiCell::PhysiCell_constants::flow_cytometry_separated_cycle_model'
/cm/shared/apps/gcc/12.3.0/bin/ld: nvc++CNZeluOJ1fgTL.ll:(.text+0x264): undefined reference to `PhysiCell::PhysiCell_constants::cycling_quiescent_model'
/cm/shared/apps/gcc/12.3.0/bin/ld: nvc++CNZeluOJ1fgTL.ll:(.text+0x270): undefined reference to `PhysiCell::PhysiCell_constants::apoptosis_death_model'
/cm/shared/apps/gcc/12.3.0/bin/ld: nvc++CNZeluOJ1fgTL.ll:(.text+0x274): undefined reference to `PhysiCell::PhysiCell_constants::necrosis_death_model'
/cm/shared/apps/gcc/12.3.0/bin/ld: nvc++CNZeluOJ1fgTL.ll:(.text+0x2d0): undefined reference to `PhysiCell::PhysiCell_constants::cycling_quiescent_model'
/cm/shared/apps/gcc/12.3.0/bin/ld: nvc++CNZeluOJ1fgTL.ll:(.text+0x2e8): undefined reference to `PhysiCell::PhysiCell_constants::apoptosis_death_model'
/cm/shared/apps/gcc/12.3.0/bin/ld: nvc++CNZeluOJ1fgTL.ll:(.text+0x308): undefined reference to `PhysiCell::PhysiCell_constants::advanced_Ki67_cycle_model'
/cm/shared/apps/gcc/12.3.0/bin/ld: nvc++CNZeluOJ1fgTL.ll:(.text+0x30c): undefined reference to `PhysiCell::PhysiCell_constants::necrosis_death_model'
/cm/shared/apps/gcc/12.3.0/bin/ld: nvc++CNZeluOJ1fgTL.ll:(.text+0x348): undefined reference to `PhysiCell::PhysiCell_constants::advanced_Ki67_cycle_model'
/cm/shared/apps/gcc/12.3.0/bin/ld: nvc++CNZeluOJ1fgTL.ll:(.text+0x36c): undefined reference to `PhysiCell::PhysiCell_constants::basic_Ki67_cycle_model'
/cm/shared/apps/gcc/12.3.0/bin/ld: nvc++CNZeluOJ1fgTL.ll:(.text+0x374): undefined reference to `PhysiCell::PhysiCell_constants::basic_Ki67_cycle_model'
/cm/shared/apps/gcc/12.3.0/bin/ld: nvc++CNZeluOJ1fgTL.ll:(.text+0x3f8): undefined reference to `PhysiCell::PhysiCell_constants::flow_cytometry_cycle_model'
/cm/shared/apps/gcc/12.3.0/bin/ld: nvc++CNZeluOJ1fgTL.ll:(.text+0x3fc): undefined reference to `PhysiCell::PhysiCell_constants::flow_cytometry_cycle_model'
```

The error is due to defining static data members in the `PhysiCell_constants.h` files wihtout reserving space for them.  Some compilers like gcc or clang are able to optimize this and do constant folding, and directly set the value at compile time with no need of a definition, but this is not quite correct and makes the code non portable. An out-of-class definition of the members is needed.

### PR DESCRIPTION
**Pull request by clasqui**
This PR fixes a bad practice in the code that makes it non-portable and prevents compiling with compilers that don't support it, specifically `nvc++`. 

Static data members in the `PhysiCell_constants.h` need an out-of-class definition somewhere in a `.cpp` file so that the storage for the static data members exists.  Some compilers do constant folding and resolve the references at compile time when there is some optimization level, but this is still non-standard and we can find cases like `nvc++` where the compiler cannot do it.

This fixes #2

### CODE REVIEW

**Comment by vincent-noel** [comment]
Hi @clasqui, many thanks for this ! 

However, since this concerns PhysiCell code, I won't merge it in this repo. But I will do my best to merge it in the next PhysiCell release !

**Comment by clasqui** [comment]
Sure! Shall I push the same PR to the PhysiCell repo?

**Comment by vincent-noel** [comment]
Yes please ! 
Out of curiosity : Was this done in order to create the test for the NVIDIA Grace CPU ? I just saw the paper

**Comment by clasqui** [comment]
Yes, we found this problem when trying to compile PhysiBoss using the last version of the nvcc for the Grace chip.
